// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1IKUYby_21x9XFo1pTX36sCyQqOejrOU',
    appId: '1:499629905592:web:1018519b42c030cd6f864d',
    messagingSenderId: '499629905592',
    projectId: 'mototaxi-3a9ec',
    authDomain: 'mototaxi-3a9ec.firebaseapp.com',
    storageBucket: 'mototaxi-3a9ec.appspot.com',
    measurementId: 'G-5XQVGPTTHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKKkgVrl2sqAG-rB8s-QbA4lS06hwAu4',
    appId: '1:499629905592:android:87ededf0715d1a056f864d',
    messagingSenderId: '499629905592',
    projectId: 'mototaxi-3a9ec',
    storageBucket: 'mototaxi-3a9ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuWKdUrK4NYX-rndvCPwUjOn3-mLHc0WI',
    appId: '1:499629905592:ios:687d5fbd0b3556916f864d',
    messagingSenderId: '499629905592',
    projectId: 'mototaxi-3a9ec',
    storageBucket: 'mototaxi-3a9ec.appspot.com',
    iosClientId: '499629905592-lmsrcgci9ckmt8diu7uk5jnmar2fi6a7.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
